#!/usr/bin/env bash
# Build ClickHouse for SmartOS/illumos and produce a distribution tarball.
#
# Usage: ci/smartos/build.sh
# Environment: CC, CXX, BUILD (build directory), OUTPUT (tarball directory).

set -euo pipefail

SRC=$(cd "$(dirname "$0")/../.." && pwd)
BUILD=${BUILD:-$SRC/build}
OUTPUT=${OUTPUT:-$BUILD}
CC=${CC:-clang}
CXX=${CXX:-clang++}

for tool in "$CC" "$CXX" cmake ninja python3 gfind ggrep gxargs; do
    command -v "$tool" >/dev/null || { echo "missing: $tool" >&2; exit 1; }
done

VERSION=$(sed -n 's/^SET(VERSION_STRING \(.*\))$/\1/p' "$SRC/cmake/autogenerated_versions.txt")

# Compilation needs ~3GB per job; the final links need far more, so link serially.
CPU_JOBS=$(psrinfo -t)
MEM_JOBS=$(( $(prtconf -m) / 3072 ))
JOBS=$(( CPU_JOBS < MEM_JOBS ? CPU_JOBS : MEM_JOBS ))
[ "$JOBS" -lt 1 ] && JOBS=1

cmake -G Ninja -S "$SRC" -B "$BUILD" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DPARALLEL_COMPILE_JOBS="$JOBS" \
    -DPARALLEL_LINK_JOBS=1 \
    -DENABLE_LIBRARIES=OFF \
    -DENABLE_RUST=OFF \
    -DENABLE_TESTS=OFF \
    -DENABLE_YAML_CPP=ON \
    -DENABLE_ICU=ON \
    -DENABLE_DATASKETCHES=ON \
    -DENABLE_ANTLR4_CPP_RUNTIME=ON \
    -DENABLE_ANTLR4_GRAMMARS=ON \
    -DENABLE_NURAFT=ON

ninja -C "$BUILD" clickhouse

STAGE="$BUILD/dist"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp "$BUILD/programs/clickhouse" "$STAGE/clickhouse"
/usr/bin/strip -x "$STAGE/clickhouse"
cp "$SRC/programs/server/config.xml" "$SRC/programs/server/users.xml" "$STAGE/"

tar czf "$OUTPUT/clickhouse-$VERSION.smartos.tar.gz" -C "$STAGE" clickhouse config.xml users.xml

ls -lh "$OUTPUT/clickhouse-$VERSION.smartos.tar.gz"
